strip db out of infra

diff --git a/infra/jobs/create-app-db-credentials.yaml b/infra/jobs/create-app-db-credentials.yaml
--- a/infra/jobs/create-app-db-credentials.yaml
+++ b/infra/jobs/create-app-db-credentials.yaml
@@ -1,7 +1,7 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: create-app-users
+  name: create-app-db-credentials-job
   namespace: payment
 spec:
   template:
@@ -47,11 +47,15 @@ spec:
           args:
             - |
               set -e
+              until pg_isready -h payment-db-postgresql -U postgres -d "$DB_NAME"; do
+                echo "Waiting for Postgres to be ready…"
+                sleep 2
+              done
               echo "
-                CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-                CREATE EXTENSION IF NOT EXISTS "btree_gin";
-                CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";
-                CREATE EXTENSION IF NOT EXISTS "plpgsql";
+                CREATE EXTENSION IF NOT EXISTS pgcrypto;
+                CREATE EXTENSION IF NOT EXISTS btree_gin;
+                CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
+                CREATE EXTENSION IF NOT EXISTS plpgsql;
                 CREATE USER \"${SERVICE_USER}\" WITH PASSWORD '${SERVICE_PASSWORD}';
                 CREATE USER \"${CONSUMER_USER}\" WITH PASSWORD '${CONSUMER_PASSWORD}';
                 GRANT CONNECT ON DATABASE $DB_NAME TO \"${SERVICE_USER}\";
@@ -61,4 +65,10 @@ spec:
                 ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"${SERVICE_USER}\";
                 ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"${CONSUMER_USER}\";"> /tmp/grant-users.sql
               export PGPASSWORD="${DB_ADMIN_PASSWORD}"
-              psql -h payment-db-postgresql -U postgres -d $DB_NAME -f /tmp/grant-users.sql
+              echo "Connecting to database… and running following script "
+              echo "Contents of /tmp/grant-users.sql:"
+              cat /tmp/grant-users.sql
+              if ! psql -h payment-db-postgresql -U postgres -d $DB_NAME --set ON_ERROR_STOP=off -f /tmp/grant-users.sql; then
+              echo "Error: psql command failed!"
+              exit 1
+              fi
