fix pamyent-consuemer

diff --git a/charts/payment-service/templates/create-app-db-credentials-job.yaml b/charts/payment-service/templates/create-app-db-credentials-job.yaml
--- a/charts/payment-service/templates/create-app-db-credentials-job.yaml
+++ b/charts/payment-service/templates/create-app-db-credentials-job.yaml
@@ -2,7 +2,9 @@ apiVersion: batch/v1
 kind: Job
 metadata:
   name: create-app-db-credentials-job
-  namespace: payment
+  namespace: {{.Release.Namespace}}
+  annotations:
+    "helm.sh/hook": pre-install,pre-upgrade
 spec:
   template:
     spec:
@@ -33,16 +35,6 @@ spec:
                 secretKeyRef:
                   name: payment-db-credentials
                   key: PAYMENT_SERVICE_APP_DB_PASSWORD
-            - name: CONSUMER_USER
-              valueFrom:
-                secretKeyRef:
-                  name: payment-db-credentials
-                  key: PAYMENT_CONSUMERS_APP_DB_USER
-            - name: CONSUMER_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: payment-db-credentials
-                  key: PAYMENT_CONSUMERS_APP_DB_PASSWORD
           command: ["/bin/sh", "-c"]
           args:
             - |
@@ -56,19 +48,19 @@ spec:
                 CREATE EXTENSION IF NOT EXISTS btree_gin;
                 CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
                 CREATE EXTENSION IF NOT EXISTS plpgsql;
-                CREATE USER \"${SERVICE_USER}\" WITH PASSWORD '${SERVICE_PASSWORD}';
-                CREATE USER \"${CONSUMER_USER}\" WITH PASSWORD '${CONSUMER_PASSWORD}';
-                GRANT CONNECT ON DATABASE $DB_NAME TO \"${SERVICE_USER}\";
-                GRANT CONNECT ON DATABASE $DB_NAME TO \"${CONSUMER_USER}\";
-                GRANT ALL ON SCHEMA public TO \"${SERVICE_USER}\";
-                GRANT ALL ON SCHEMA public TO \"${CONSUMER_USER}\";
-                ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"${SERVICE_USER}\";
-                ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO \"${CONSUMER_USER}\";"> /tmp/grant-users.sql
+                DO \$\$
+                BEGIN
+                  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${SERVICE_USER}') THEN
+                    EXECUTE 'CREATE USER \"${SERVICE_USER}\" WITH PASSWORD ''${SERVICE_PASSWORD}''';
+                  END IF;
+                END
+                \$\$;
+              " > /tmp/create-users.sql
               export PGPASSWORD="${DB_ADMIN_PASSWORD}"
               echo "Connecting to database… and running following script "
-              echo "Contents of /tmp/grant-users.sql:"
-              cat /tmp/grant-users.sql
-              if ! psql -h payment-db-postgresql -U postgres -d $DB_NAME --set ON_ERROR_STOP=off -f /tmp/grant-users.sql; then
-              echo "Error: psql command failed!"
-              exit 1
+              echo "Contents of /tmp/create-users.sql:"
+              cat /tmp/create-users.sql
+              if ! psql -h payment-db-postgresql -U postgres -d $DB_NAME --set ON_ERROR_STOP=off -f /tmp/create-users.sql; then
+                echo "Error: psql command failed!"
+                exit 1
               fi
